### ISSUE TITLE
Add chain inspection/validation tools?

### ISSUE THREAD

**Issue by cparmet** [danieleongari/pandas-chaining-ninja#23]
@danieleongari Love this cheat sheet! Taught me about unpacking dataframes in assign. Brilliant! Thanks for putting it together.

I wonder if it's worth referencing one or more tools that can assist inspecting and debugging method chains? I know Tom Augsperger, whose [post on Pandas method chaining](https://tomaugspurger.net/posts/method-chaining/) showed me the light, recommends [Bulwark](https://github.com/zaxr/bulwark). I also made [`pandas-checks`](https://github.com/cparmet/pandas-checks/) to package up some methods from `.pipe()` lines I was recreating in many of my projects.

**Comment by danieleongari** [comment]
solved b1912c296b313d830e61119fda3e2eba20ca65fd
